module.exports={
  db:{
  uri:"mongodb+srv://Timileyin:timileyin-admin@practicecluster.3le1x.mongodb.net/book-lib?retryWrites=true&w=majority"
  }, 
  cors:{
  origin:"*"
  }, 
  session:{
    secret:"mySecretKey"
  }
}